export const USER = Object.freeze({
  CREATE_RANDOM_USER: 'CREATE_RANDOM_USER',
  CREATE_USER: 'CREATE_USER',
  GET_USER: 'GET_USER',
  DELETE_USER: 'DELETE_USER',
  UPDATE_USER: 'UPDATE_USER',
  SELECT_USER: 'SELECT_USER',
})